version: "2.1"

services:
    db:
        restart: on-failure
        container_name: SRPA_mysql_production
        image: mysql
        command: ['--character-set-server=utf8', '--collation-server=utf8_general_ci']
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=SRPA
        ports:
            - "3308:3306"
        logging:
            driver: none
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            timeout: 5s
            retries: 10
    srpa_django:
        restart: on-failure
        container_name: SRPA_django
        image: youchend/srpa_django
        build: .
        ports:
            - "8000:8000"
        depends_on:
            db:
                condition: service_healthy
        links:
            - db:db
